############################################################
# Dockerfile to build shibecoind container images
# Based on Ubuntu
############################################################

FROM ubuntu:14.04
MAINTAINER laudney

RUN apt-get update
RUN apt-get install -y git make g++ python-leveldb libboost-all-dev libssl-dev libdb++-dev pkg-config libminiupnpc-dev wget xz-utils
RUN apt-get clean

RUN adduser shibecoin --disabled-password
USER shibecoin

WORKDIR /home/shibecoin
RUN mkdir bin src
RUN echo PATH=\"\$HOME/bin:\$PATH\" >> .bash_profile

WORKDIR /home/shibecoin/src
RUN git clone https://github.com/shibecoin-project/shibecoin.git

WORKDIR	/home/shibecoin/src/shibecoin/src
RUN make -f makefile.unix
RUN strip shibecoind
RUN cp -f shibecoind /home/shibecoin/bin/
RUN make -f makefile.unix clean

WORKDIR	 /home/shibecoin
RUN mkdir .shibecoin
RUN cp -f src/shibecoin/contrib/docker/ShibeCoin.conf .shibecoin/

WORKDIR /home/shibecoin/.shibecoin
RUN wget -q https://github.com/shibecoin-project/shibecoin/releases/download/v1.3.1.2/bootstrap.dat.xz

ENV HOME /home/shibecoin
EXPOSE 8332
USER shibecoin
